# Generated by Django 6.1 on 2026-08-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_student_prenom_postnom_nom_matricule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['nom', 'prenom']},
        ),
    ]
