# Generated by Django 6.1 on 2026-08-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0006_add_coordinate_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='path_geometry',
            field=models.JSONField(blank=True, help_text="Points [lat, lon] de l'itinéraire routier réel (OSRM), au format JSON.", null=True),
        ),
    ]
