# Generated by Django 6.1 on 2026-08-15 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0008_student_user_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver_user',
            field=models.OneToOneField(blank=True, help_text='Compte de connexion du chauffeur associé à ce bus.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_bus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='is_taken',
            field=models.BooleanField(default=False, help_text="True si l'élève a été pris en charge par le bus (ramassage confirmé)."),
        ),
    ]
