# Generated by Django 6.1 on 2026-08-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0009_driver_bus_and_student_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='last_latitude',
            field=models.FloatField(blank=True, help_text='Dernière latitude GPS reçue du téléphone du chauffeur.', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_longitude',
            field=models.FloatField(blank=True, help_text='Dernière longitude GPS reçue du téléphone du chauffeur.', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_position_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage de la dernière position GPS reçue.', null=True),
        ),
    ]
