# Generated by Django 6.1 on 2026-08-15 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0010_bus_last_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_notified',
            field=models.BooleanField(default=False, help_text="True si un SMS d'approche (< 100 m) a déjà été envoyé au parent."),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Téléphone du parent (ex. +243...).', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_user',
            field=models.ForeignKey(blank=True, help_text="Compte de connexion du parent (facultatif — l'élève peut se connecter avec son matricule).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
