# Generated by Django 6.1 on 2026-08-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0012_multischool_and_password_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Date de création de l'école.", null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, help_text="False si l'école est désactivée par l'administration générale (accès bloqué, mais données conservées)."),
        ),
    ]
