# Generated by Django 6.1 on 2026-08-15 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0013_school_created_at_school_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Position GPS du domicile, définie par le parent lors de sa première connexion.', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Position GPS du domicile, définie par le parent lors de sa première connexion.', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
