# Generated by Django 6.1 on 2026-08-15 22:08

import django.db.models.deletion
import routing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0014_alter_student_latitude_alter_student_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Vidange', 'Vidange'), ('Freins', 'Freins'), ('Pneumatiques', 'Pneumatiques'), ('Contrôle technique', 'Contrôle technique'), ('Autre', 'Autre')], max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_effectuee', models.DateField(default=routing.models._local_date)),
                ('prochaine_echeance_km_ou_date', models.CharField(blank=True, help_text='Ex : 5000 km ou 15/12/2026.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='routing.bus')),
            ],
            options={
                'ordering': ['-date_effectuee', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(choices=[('Embouteillage', 'Embouteillage'), ('Panne', 'Panne'), ('Accident', 'Accident'), ('Excès de vitesse', 'Excès de vitesse'), ('Autre', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Description libre (optionnelle).')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='routing.bus')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=routing.models._local_date)),
                ('reason', models.CharField(blank=True, help_text='Motif optionnel (ex : maladie).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='routing.student')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_absence_per_day')],
            },
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_kmh', models.FloatField(default=0.0, help_text='Vitesse instantanée estimée (km/h).')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to='routing.bus')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['bus', 'timestamp'], name='routing_gps_bus_id_c2bb66_idx')],
            },
        ),
    ]
