# Generated by Django 6.1 on 2026-08-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0015_busmaintenance_incident_absence_gpslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver_connected',
            field=models.BooleanField(default=False, help_text="True si le chauffeur est connecté (le bus apparaît alors en direct sur la carte de l'école ; il disparaît à la déconnexion)."),
        ),
    ]
