# Generated by Django 6.1 on 2026-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0016_bus_driver_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='overcapacity_alert',
            field=models.BooleanField(default=False, help_text="True si l'élève a une position GPS mais qu'aucun bus actif de son école n'a de capacité disponible (tous les bus proches sont complets)."),
        ),
    ]
