# Generated by Django 6.1 on 2026-08-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0017_student_overcapacity_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='speed_kmh',
            field=models.FloatField(default=0.0, help_text='Dernière vitesse connue du bus (km/h), envoyée par le téléphone du chauffeur.'),
        ),
    ]
